---
apiVersion: v1
kind: Namespace
metadata:
  name: <APP-NS>-<CLUSTER-NAME>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helloworld-channel
  namespace: <APP-NS>-<CLUSTER-NAME>
spec:
  type: GitHub
  pathname: https://github.com/open-cluster-management/application-samples.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: helloworld-app-placement
  namespace: <APP-NS>-<CLUSTER-NAME>
  labels:
    app: helloworld-app
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      name: <CLUSTER-NAME>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: helloworld-app-subscription
  namespace: <APP-NS>-<CLUSTER-NAME>
  labels:
    app: helloworld-app
  annotations:
    apps.open-cluster-management.io/github-path: helloworld
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: <APP-NS>-<CLUSTER-NAME>/helloworld-channel
  placement:
    placementRef:
      name: helloworld-app-placement
      kind: PlacementRule
