---
apiVersion: v1
kind: Namespace
metadata:
  name: <APP-NS>-<CLUSTER-NAME>
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: <APP-NS>-<CLUSTER-NAME>
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      name: <CLUSTER-NAME>
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: predev-ch
  namespace: <APP-NS>-<CLUSTER-NAME>
  labels:
    app: nginx-app-details
spec:
  type: HelmRepo
  pathname: https://charts.helm.sh/stable/
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx
  namespace: <APP-NS>-<CLUSTER-NAME>
  labels:
    app: nginx-app-details
spec:
  channel: <APP-NS>/predev-ch
  name: nginx-ingress
  packageFilter:
    version: "1.36.x"
  placement:
    placementRef:
      kind: PlacementRule
      name: towhichcluster
